services:
    postgres:
        image: postgres:15
        container_name: ${DB_NAME}
        restart: always
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "${DB_PORT}:5432"
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: