services:
  postgres:
      image: postgres:15
      container_name: ${DB_NAME}
      restart: always
      environment:
          POSTGRES_USER: ${DB_USER}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          POSTGRES_DB: ${DB_NAME}
      ports:
          - "${DB_PORT}:5432"
      volumes:
          - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
      image: dpage/pgadmin4
      container_name: keysphere_pgadmin
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@keysphere.com
        PGADMIN_DEFAULT_PASSWORD: admin123
      ports:
        - '5050:80'
      depends_on:
        - postgres
volumes:
  postgres_data: